---
- hosts: server1
  become: true
  remote_user: admin

  tasks:
  - name: Copy war
    ansible.builtin.copy:
      src: "{{ lookup('ansible.builtin.env', 'WORKSPACE') }}/target/applicationPetstore.war"
      dest: /home/admin

  - name: Deploy war with jboss-cli.sh
    ansible.builtin.shell: |
      /home/admin/jboss-eap-7.4/bin/jboss-cli.sh -c --command="undeploy applicationPetstore.war"
      /home/admin/jboss-eap-7.4/bin/jboss-cli.sh -c --command="deploy /home/admin/applicationPetstore.war"

  # - name: Deploy war
  #   community.general.jboss:
  #     src: /home/admin/applicationPetstore.war
  #     deploy_path: /home/admin/jboss-eap-7.4/standalone/deployments
  #     deployment: applicationPetstore.war
  #     state: present

  - name: Remove war
    ansible.builtin.file:
      path: /home/admin/applicationPetstore.war
      state: absent